app/src/main/java/com/tnco/runar/adapters/OnboardViewPagerAdapter.kt
app/src/main/java/com/tnco/runar/controllers/AnalyticsHelper.kt
app/src/main/java/com/tnco/runar/enums/AnalyticsEvent.kt
app/src/main/java/com/tnco/runar/presentation/viewmodel/FavouriteViewModel.kt
app/src/main/java/com/tnco/runar/ui/activity/OnboardActivity.kt
app/src/main/java/com/tnco/runar/ui/dialogs/CancelDialog.kt
app/src/main/java/com/tnco/runar/ui/fragments/FavouriteFragment.kt
app/src/main/java/com/tnco/runar/ui/fragments/GeneratorBackground.kt
app/src/main/java/com/tnco/runar/ui/fragments/GeneratorFinal.kt
app/src/main/java/com/tnco/runar/ui/fragments/GeneratorFragment.kt
app/src/main/java/com/tnco/runar/ui/fragments/GeneratorMagicRune.kt
app/src/main/java/com/tnco/runar/ui/fragments/GeneratorStartFragment.kt
app/src/main/java/com/tnco/runar/ui/fragments/LayoutDescriptionFragment.kt
app/src/main/java/com/tnco/runar/ui/fragments/LayoutFragment.kt
app/src/main/java/com/tnco/runar/ui/fragments/LayoutInitFragment.kt
app/src/main/java/com/tnco/runar/ui/fragments/LayoutInterpretationFragment.kt
app/src/main/java/com/tnco/runar/ui/fragments/LayoutProcessingFragment.kt
app/src/main/java/com/tnco/runar/ui/fragments/LibraryFragment.kt
app/src/main/java/com/tnco/runar/ui/fragments/RunePatternGenerator.kt
app/src/main/java/com/tnco/runar/utils/AnalyticsConstants.kt
app/src/main/java/com/tnco/runar/utils/AnalyticsUtils.kt
build.gradle
gradle/wrapper/gradle-wrapper.properties

Сделал рефакторинг и добавил новые ивенты в firebase для генератора.
---
Добавил комент в джире к задаче, что на данный момент реализовано.

RUN71 - analytics

---

.github/workflows/main.yml

В общих чертах описать пулл реквест (2-3 предложения)
Я делаю такую-то фичу вот такие вот экраны.
Описать это готовая фича или подготовка или рефакторинг.
---
Может быть это драфтовый пулл реквест, что бы понять правильное ли направлении.
Например "Сделал пример стилизации компонента, не уверен что в правильном направлении иду, гляньте плез. Нужен общий ревью. не влезая в детали"
то в этом блоке стоит описать это... что не нужно придираться к мелочам, что пока норм если есть логи и коментарии.
Если это готовый пулл реквест, то это тоже лучше описать тут.
"ПР полностью готов к финальному ревью. Нужно проверить всё"
---
Пару скриншотов помогут легче вникнуть в изменения. Код ревью пройдет быстрее
---

Build app on push

---

app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
app/src/main/res/values/colors.xml

Сверила обновления дизайна библиотеки. Причесала код.

check the library ui updates and improve the code

---

app/src/main/java/com/tnco/runar/ui/fragment/FavouriteFragment.kt
app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
app/src/main/res/values/colors.xml

- Сравнила дизайн Избранных с дизайном с фигмы
- Подкорректировала код

Check ui updates and decorate code in Favourites fragment

---

app/src/main/java/com/tnco/runar/ui/fragment/AboutAppFragment.kt
app/src/main/java/com/tnco/runar/ui/fragment/SettingsFragment.kt
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml

1. Привел высоту элементов списка в соответствие с GuideLine. 
2. Поправил шрифты.
3. Уменьшил вложенность макетов UI.
4. Вынес хардкод цветов и падингов в соответствующие файлы ресурсов.

Run 82/updating UI/settings

---

app/src/main/res/values-ru/strings.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

Разрешил конфликт с ресурсами в ПР "Generator with fix".

Resolving conflicts with resources in PR Generator with fix

---

app/build.gradle

Подготовила build gradle для добавления генератора.

Build gradle changes

---

app/src/main/java/com/tnco/runar/ui/fragment/LayoutInitFragment.kt

Подчищаю код, убираю копипасту

improved the code

---

app/src/main/java/com/tnco/runar/ui/fragment/BackgroundAdapter.kt
app/src/main/java/com/tnco/runar/ui/fragment/GeneratorBackground.kt
app/src/main/java/com/tnco/runar/ui/viewmodel/MainViewModel.kt
app/src/main/res/drawable/backround_background.xml
app/src/main/res/layout/backgroung_generato_selected.xml

https://user-images.githubusercontent.com/43334039/187641266-319e52ae-aac7-4779-a42e-27a550f416de.mp4

Fixed too long generation of the result of getting background pictures

---

app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
app/src/main/java/com/tnco/runar/ui/viewmodel/LibraryViewModel.kt

Удалил хлебные крохи из раздела библиотеки

Remove breadcrumbs from Library

---

app/src/main/res/layout/activity_main.xml

Изменил изображение бекграунда в генераторе

Change bg image on generator

---

app/src/main/res/drawable-v24/generator_start_button.xml
app/src/main/res/layout-xhdpi/fragment_generator_start.xml

Изменил стиль кнопки выбора случайных рун
было:
стало:

RUN-119 / Incorrect button style on generator rune choose page

---

app/src/main/res/values/strings.xml

Обновил стринговый ресурс/ccылку для английской версии

Fix strings.xml

---

app/src/main/res/values/strings.xml

Исправил грамматическую ошибку в стринговом ресурсе (en).
Проверил на физическом устройстве.

Run 133/update strings.xml

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/tnco/runar/ui/fragment/GeneratorFinal.kt

Исправила краш приложения, который возникал при попытке поделиться сгенерированными обоями в генераторе.

RUN-146: Sharing a pattern crash

---

app/src/main/java/com/tnco/runar/ui/adapter/RunesGeneratorAdapter.kt
app/src/main/java/com/tnco/runar/ui/fragment/GeneratorFinal.kt
app/src/main/java/com/tnco/runar/ui/fragment/GeneratorStartFragment.kt

-Исправила краш, который возникал в генераторе при нажатии на кнопку "Сгенерировать руны" пока руны еще не подгрузились. Краш возникал после чистки кэша приложения Runar.
-В процессе тестирования исправления бага run-153 обнаружила уязвимость в моей прошлой задаче run-146, всё исправила. 
краш случался при попытке поделиться сгенерированными обоями, я его исправила, но когда сегодня решила проверить снова, почистив при этом кэши, приложение упало. это произошло из за неточности в проверке, которую я написала вчера.

Fixed crashes run-153, 146: crash when loading runes in Generator. 

---

app/src/main/java/com/tnco/runar/ui/fragment/BackgroundAdapter.kt
app/src/main/java/com/tnco/runar/ui/fragment/GeneratorBackground.kt
app/src/main/java/com/tnco/runar/ui/fragment/GeneratorMagicRune.kt
app/src/main/java/com/tnco/runar/ui/fragment/RunePatternGenerator.kt
app/src/main/java/com/tnco/runar/ui/viewmodel/MainViewModel.kt

Исправил падения приложения при:
1. Генерации с рандомными рунами и по выбраному узору
2. Принудительном закрытии на любом этапе и повторной генерации

Fixing application crash during generation (RUN-69)

---

app/src/main/java/com/tnco/runar/ui/fragment/LayoutInterpretationFavFragment.kt
app/src/main/java/com/tnco/runar/ui/fragment/LayoutInterpretationFragment.kt
app/src/main/java/com/tnco/runar/ui/viewmodel/InterpretationFavViewModel.kt
app/src/main/res/layout/fragment_layout_interpretation_fav.xml

Изменил отображение процентов удачи на текст в избранном

RUN-152 change luck percentages to text for favourites runic draws

---

app/src/main/res/layout-sw600dp/fragment_generator_start.xml
app/src/main/res/layout-sw720dp/fragment_generator_start.xml

fix problrem with button in generator (tablets)

RUN-129 / Incorrect display of elements in Generator (tablets)

---

app/src/main/java/com/tnco/runar/data/remote/BackendApiInterface.kt
app/src/main/java/com/tnco/runar/data/remote/RetrofitClient.kt
app/src/main/java/com/tnco/runar/repository/backend/BackendRepository.kt
app/src/main/java/com/tnco/runar/ui/fragment/GeneratorBackground.kt
app/src/main/java/com/tnco/runar/ui/fragment/GeneratorFinal.kt
app/src/main/java/com/tnco/runar/ui/fragment/GeneratorMagicRune.kt
app/src/main/java/com/tnco/runar/ui/fragment/RunePatternGenerator.kt
app/src/main/java/com/tnco/runar/ui/viewmodel/MainViewModel.kt
app/src/main/res/layout/rune_pattern_generator.xml

- Handled the situation of generating selected runes without internet on the GeneratorMagicRune and RunePatternGenerator windows
- Reduced waiting time to load from 5 minutes to 40 seconds.

Fix crashing GeneratorMagicRune and RunePatternGenerator without internet

---

app/src/main/java/com/tnco/runar/data/remote/BackendApiInterface.kt
app/src/main/java/com/tnco/runar/repository/backend/BackendRepository.kt
app/src/main/java/com/tnco/runar/ui/fragment/GeneratorBackground.kt
app/src/main/java/com/tnco/runar/ui/fragment/GeneratorFinal.kt
app/src/main/java/com/tnco/runar/ui/viewmodel/MainViewModel.kt
app/src/main/res/layout/fragment_generator_background.xml
app/src/main/res/layout/rune_pattern_generator.xml

- Handled the situation of generating background images without internet on the GeneratorBackground window

Fix crashing GeneratorBackground without internet

---

app/src/main/java/com/tnco/runar/ui/fragment/GeneratorFinal.kt
app/src/main/res/values-ru/strings.xml
app/src/main/res/values/strings.xml

1. пофиксил двойное сохранение 
2. изменил директорию с загрузок на картинки
3. рефакторинг деприкейтэд методов проверки пермишенов

RUN-158 fix double save picture after create pattern from generator

---

app/src/main/res/layout/fragment_layout_interpretation.xml

Реализация - добавил paddingBottom к тексту.

RUN-162 / second commit

---

app/src/main/res/values/strings.xml

Change en description of onboard (generator)

RUN-171 / Update the wording for the generator page [ENG version] [android]

---

.github/workflows/main-merge.yml
.github/workflows/main-pr.yml

В общих чертах описать пулл реквест (2-3 предложения)
Я делаю такую-то фичу вот такие вот экраны.
Описать это готовая фича или подготовка или рефакторинг.
---
Может быть это драфтовый пулл реквест, что бы понять правильное ли направлении.
Например "Сделал пример стилизации компонента, не уверен что в правильном направлении иду, гляньте плез. Нужен общий ревью. не влезая в детали"
то в этом блоке стоит описать это... что не нужно придираться к мелочам, что пока норм если есть логи и коментарии.
Если это готовый пулл реквест, то это тоже лучше описать тут.
"ПР полностью готов к финальному ревью. Нужно проверить всё"
---
Пару скриншотов помогут легче вникнуть в изменения. Код ревью пройдет быстрее
---

Rename file on CI/CD

---

.github/workflows/main-merge.yml
.github/workflows/main-pr.yml

В общих чертах описать пулл реквест (2-3 предложения)
Я делаю такую-то фичу вот такие вот экраны.
Описать это готовая фича или подготовка или рефакторинг.
---
Может быть это драфтовый пулл реквест, что бы понять правильное ли направлении.
Например "Сделал пример стилизации компонента, не уверен что в правильном направлении иду, гляньте плез. Нужен общий ревью. не влезая в детали"
то в этом блоке стоит описать это... что не нужно придираться к мелочам, что пока норм если есть логи и коментарии.
Если это готовый пулл реквест, то это тоже лучше описать тут.
"ПР полностью готов к финальному ревью. Нужно проверить всё"
---
Пару скриншотов помогут легче вникнуть в изменения. Код ревью пройдет быстрее
---

Rename github actions

---

.github/workflows/main-merge.yml
.github/workflows/main-pr.yml
app/src/main/java/com/tnco/runar/ui/fragment/RunePatternGenerator.kt

Create ability to swipe images on "Pattern Create" view
so that, user will have additional control for choosing pattern
------
It's just improvement without tasks

Create ability to swipe on "Pattern Create" view

---

.github/workflows/main-merge.yml
.github/workflows/main-pr.yml

Should not pass html tags to telegram bot.
<dmowski@yandex.ru> in commit messages is parsed as html tag
В общих чертах описать пулл реквест (2-3 предложения)
Я делаю такую-то фичу вот такие вот экраны.
Описать это готовая фича или подготовка или рефакторинг.
---
Может быть это драфтовый пулл реквест, что бы понять правильное ли направлении.
Например "Сделал пример стилизации компонента, не уверен что в правильном направлении иду, гляньте плез. Нужен общий ревью. не влезая в детали"
то в этом блоке стоит описать это... что не нужно придираться к мелочам, что пока норм если есть логи и коментарии.
Если это готовый пулл реквест, то это тоже лучше описать тут.
"ПР полностью готов к финальному ревью. Нужно проверить всё"
---
Пару скриншотов помогут легче вникнуть в изменения. Код ревью пройдет …

Sanitize telegram message

---

README.md

Сделал более читабельную верстку readme файла

Format readme into tables

---

app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
app/src/main/java/com/tnco/runar/ui/viewmodel/LibraryViewModel.kt
app/src/main/res/values-ru/strings.xml
app/src/main/res/values/strings.xml

При отсутствии интернета в библиотеке и первом открытии приложения высвечивается тост оповещающий пользователя о необходимости подключения к интернету для подгрузки картинок.

Run 124 - The absence of displaying images in library when offline and cache empty

---

app/src/main/res/values-ru/strings.xml

RUN-193/fix misprint on the "Favourites" page as it's indicated in Figma

---

app/src/main/res/values-ru/strings.xml

fix: change wording

---

app/src/main/java/com/tnco/runar/ui/adapter/RunesGeneratorAdapter.kt
app/src/main/java/com/tnco/runar/ui/fragment/GeneratorStartFragment.kt
app/src/main/res/values/dimens.xml

Darkening of the selected rune in Generator

---

app/src/main/java/com/tnco/runar/ui/fragment/LayoutInitFragment.kt

Fixed a bug with repeating random runes
[device-2022-12-08-131609.webm](https://user-images.githubusercontent.com/71641200/206372124-8786a563-a668-4da0-bdd1-da86499aca35.webm)

Run 253 runic draws repeating runes in the layouts

---

app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt

Сделала табы переключения между книгами и аудио в разделе библиотеки.

run-19: create the tabs in Library

---

app/build.gradle
app/proguard-rules.pro
app/src/main/java/com/tnco/runar/data/remote/BackgroundInfo.kt
app/src/main/java/com/tnco/runar/data/remote/En.kt
app/src/main/java/com/tnco/runar/data/remote/HashResponse.kt
app/src/main/java/com/tnco/runar/data/remote/LibraryResponse.kt
app/src/main/java/com/tnco/runar/data/remote/Ru.kt
app/src/main/java/com/tnco/runar/data/remote/RunesResponse.kt
app/src/main/java/com/tnco/runar/data/remote/UserResponse.kt

https://runar.atlassian.net/browse/RUN-255
enable minify for release and debug variants, add annotation SerializedName to retrofit models

RUN-255 CI/CD: Connect and set up R8 (Part 1)

---

app/src/main/java/com/tnco/runar/ui/activity/MainActivity.kt

Fixed bottom navigation bar for "About" page.

Fixed bottom navigation bar for "About" page.

---

app/src/main/java/com/tnco/runar/ui/fragment/LibraryCompose.kt

- Пофиксила баг скроллстейта в Библиотеке (приложение падало при клике на кнопку "Назад")
- Прорефакторила код

Fixing a scroll-bug

---

app/src/main/java/com/tnco/runar/ui/fragment/LibraryCompose.kt

Created a function for scroll indication

Create fun ScrollBars

---

app/build.gradle
app/src/main/AndroidManifest.xml

add uses-sdk to manifest.xml
change compileOptions to java 11, buildToolsVersion 33

RUN-262 add uses-sdk to manifest.xml

---

app/src/main/res/layout/rune_pattern_generator.xml

RUN-257 / UI Generator button "Далее"/"Next"

---

.github/workflows/main-pr.yml

Add link to PR on CI/CD for notification

Add link to PR on CI/CD for notification

---

app/build.gradle
app/src/main/java/com/tnco/runar/ui/fragment/LibraryRunesCompose.kt
app/src/main/res/values/colors.xml

Changed the background and border color to the one in the figma

Run-281/[UI][Library][RuneDescription][tags]/changed tags color

---

.github/workflows/main-merge.yml
.github/workflows/main-pr.yml

Delete "*", "~", "_" symbols from commit message in merge script

Fix bug with pair symbols in CI/CD script

---

app/src/main/java/com/tnco/runar/ui/fragment/ConnectivityErrorFragment.kt
app/src/main/java/com/tnco/runar/util/InternalDeepLink.kt
app/src/main/res/navigation/runic_draws.xml

Исправлена ошибка возникающая при открытии у пользователя экрана с ошибкой 
Так же исправлена ошибка связанная с двойным кликом (если с экрана ошибки нажать два раза на кнопку назад. То вернёшься опять на экран ошибки)
---
---

RUN-337 Unable to return to home page

---

app/src/main/java/com/tnco/runar/App.kt
app/src/main/java/com/tnco/runar/feature/MusicController.kt
app/src/main/java/com/tnco/runar/repository/SharedPreferencesRepository.kt
app/src/main/java/com/tnco/runar/repository/backend/BackendRepository.kt
app/src/main/java/com/tnco/runar/services/PushService.kt
app/src/main/java/com/tnco/runar/ui/activity/MainActivity.kt
app/src/main/java/com/tnco/runar/ui/activity/SplashActivity.kt
app/src/main/java/com/tnco/runar/ui/fragment/GeneratorStartFragment.kt
app/src/main/java/com/tnco/runar/ui/fragment/LayoutInterpretationFragment.kt
app/src/main/java/com/tnco/runar/ui/viewmodel/InterpretationViewModel.kt
app/src/main/java/com/tnco/runar/ui/viewmodel/MainViewModel.kt
app/src/main/java/com/tnco/runar/ui/viewmodel/SettingsViewModel.kt
app/src/main/java/com/tnco/runar/ui/viewmodel/SplashViewModel.kt

add SharedPreferencesRepository to the DI graph

RUN-236 Add DI to the project

---

app/src/main/java/com/tnco/runar/repository/DatabaseRepository.kt
app/src/main/java/com/tnco/runar/repository/LanguageRepository.kt
app/src/main/java/com/tnco/runar/repository/SharedPreferencesRepository.kt
app/src/main/java/com/tnco/runar/repository/data_store/DataStorePreferences.kt
app/src/main/java/com/tnco/runar/ui/fragment/GeneratorStartFragment.kt
app/src/main/java/com/tnco/runar/ui/viewmodel/MainViewModel.kt
app/src/main/java/com/tnco/runar/ui/viewmodel/SettingsViewModel.kt
app/src/main/java/com/tnco/runar/ui/viewmodel/SplashViewModel.kt

move the logic for getting the current language to a repository,
fix the bug with a language selection in GeneratorStartFragment,
get rid of redundant code left over from the old implementation

RUN-349 Implementation of per-app language preferences

---

app/src/main/java/com/tnco/runar/repository/data_store/DataStorePreferences.kt
app/src/main/java/com/tnco/runar/ui/activity/MainActivity.kt
app/src/main/java/com/tnco/runar/ui/viewmodel/DeveloperOptionsViewModel.kt

fix a problem with the initial state of the switchers
Problem description:
The first time the application was launched, the audio tales switcher was not initialised when entering the library.

 RUN-280 Change the_storage location of developer switchers states

---

.github/workflows/main-merge.yml
.github/workflows/main-pr.yml
.github/workflows/test.yml

Выпилил тестирование на многих API.
Сейчас тесты будут проходить только на API 29

Fix failed test on merge action

---

app/src/main/java/com/tnco/runar/ui/fragment/AboutAppFragment.kt
app/src/main/java/com/tnco/runar/ui/layouts/AboutAppFragmentLayout.kt
app/src/main/java/com/tnco/runar/ui/widgets/AboutText.kt
app/src/main/java/com/tnco/runar/ui/widgets/TopBarIcon.kt

RUN-238 Refactoring of components with Compose functions

---

app/src/main/java/com/tnco/runar/ui/fragment/LibraryCompose.kt
app/src/main/java/com/tnco/runar/ui/screenCompose/componets/ComposeComponents.kt

добавил новый апп бар в библиотеку

New app bar in library

---

app/src/main/java/com/tnco/runar/ui/fragment/FavouriteFragment.kt
app/src/main/java/com/tnco/runar/ui/screenCompose/componets/ComposeComponents.kt

https://runar.atlassian.net/browse/RUN-406
при добавлении мусорки избранное не по по центру и выравнивается только когда появляется мусорка 
была даже добавлена прозрачная картинка для решения
но компоуз не видит ее пока она прозрачная, так же было когда на саму мусорку прозрачность накладывал.
паддинги не вариант тк сломается на других экранах.
какие есть предложения по решению проблемы

RUN / 406 add delete icon

---

app/src/main/java/com/tnco/runar/ui/fragment/AboutAppFragment.kt
app/src/main/java/com/tnco/runar/ui/fragment/FavouriteFragment.kt

delete nav bar in favorite, settings and about

---

app/src/main/AndroidManifest.xml

BillingAbility

---

app/src/main/java/com/tnco/runar/data/local/AppDao.kt
app/src/main/java/com/tnco/runar/repository/DatabaseRepository.kt
app/src/main/java/com/tnco/runar/ui/fragment/LibraryCompose.kt
app/src/main/java/com/tnco/runar/ui/viewmodel/LibraryViewModel.kt

…bug where the descriptions of some runs are not displaying
--- 
- Add LiveData to observe changes in the database(library) 
- fix the bug where the descriptions of some runs are not displaying
---

fix the bug where the descriptions of some runs are not displaying

---

app/src/main/java/com/tnco/runar/data/local/AppDao.kt
app/src/main/java/com/tnco/runar/repository/DatabaseRepository.kt
app/src/main/java/com/tnco/runar/ui/fragment/LibraryCompose.kt
app/src/main/java/com/tnco/runar/ui/viewmodel/LibraryViewModel.kt

--- заменим LiveData на List, чтобы сохранить состояние скрола, при повторном вызове composable функции.
---

changing LiveData with simple List(library)

---

app/src/main/java/com/tnco/runar/ui/screenCompose/MenuCompose.kt

add subscription fragment in debug

---

app/src/main/java/com/tnco/runar/ui/fragment/PrivacyPolicyCompose.kt

1. Выравнен title в английской версии

update title privacy policy
